version: 2
registries:
  docker-elastic:
    type: docker-registry
    url: https://docker.elastic.co
    username: ${{secrets.ELASTIC_DOCKER_USERNAME}}
    password: ${{secrets.ELASTIC_DOCKER_PASSWORD}}

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      # For mimic-response, ignore all versions https://github.com/elastic/apm-agent-nodejs/pull/3349#issuecomment-1549517238
      - dependency-name: "mimic-response"
      # aws-sdk packages update so frequently, we don't want anything but majors.
      - dependency-name: "aws-sdk"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "@aws-sdk/*"
        update-types: ["version-update:semver-minor"]
      # Babel packages are numerous and our tests don't depend on finer details.
      - dependency-name: "@babel/*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "@types/*"
        update-types: ["version-update:semver-patch"]
      # Packages whose major versions have dropped support for Node.js versions
      # that this package needs.
      - dependency-name: "glob" # glob@10 min is 14.20, we need >=14.17; glob@11 dropped 14, 16, 18
        update-types: ["version-update:semver-major"]
      - dependency-name: "lru-cache" # later lru-cache@10.x toyed with dropping 14.x, we pin to a specific early 10.x; lru-cache@11 dropped 14, 16, 18
      - dependency-name: "rimraf" # rimraf@5 min is 14.20, we need >=14.17; rimraf@6 dropped 14, 16, 18
        update-types: ["version-update:semver-major"]
      # Packages whose newer versions are not supported by the agent
      - dependency-name: "redis" # support is >=2.0.0 <5
      - dependency-name: "next" # support is >=12.0.0 <13.3.0
    groups:
      aws-sdk:
        dependency-type: "development"
        patterns:
        - "aws-sdk"
        - "@aws-sdk/*"
      babel:
        dependency-type: "development"
        patterns:
        - "@babel/*"
      apollo:
        dependency-type: "development"
        patterns:
        - "apollo-server-*"
        - "@apollo/*"
      eslint:
        dependency-type: "development"
        patterns:
        - "eslint*"

  - package-ecosystem: "npm"
    directory: "/test/instrumentation/azure-functions/fixtures/azfunc3"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/test/instrumentation/azure-functions/fixtures/azfunc4"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/test/opentelemetry-bridge"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/test/opentelemetry-metrics/fixtures"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/examples/opentelemetry-bridge"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/examples/opentelemetry-metrics"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    groups:
      github-actions:
        patterns:
          - "*"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    registries: "*"
    schedule:
      interval: "weekly"
